export const movieList = [
    {
        genres: "Horror Thriller",
        resourceId: 663712,
        poster: "https://image.tmdb.org/t/p/w342/yw8NQyvbeNXoZO6v4SEXrgQ27Ll.jpg",
        title: "Terrifier 2",
        voteAverage: 7.5,
    },
    {
        genres: "Thriller",
        resourceId: 985939,
        poster: "https://image.tmdb.org/t/p/w342/spCAxD99U1A6jsiePFoqdEcY0dG.jpg",
        title: "Fall",
        voteAverage: 7.3,
    },
    {
        genres: "Drama Thriller Horror",
        resourceId: 848058,
        poster: "https://image.tmdb.org/t/p/w342/pIFeu5gF7ofAxI9NqrWbJAjjKn6.jpg",
        title: "Piggy",
        voteAverage: 7,
    },
    {
        genres: "Science Fiction Horror Action",
        resourceId: 870096,
        poster: "https://image.tmdb.org/t/p/w342/kl80N1g69v9QXe1wvkFza31WhD4.jpg",
        title: "Restart The Earth",
        voteAverage: 7,
    },
    {
        genres: "Action Adventure Science Fiction",
        resourceId: 505642,
        poster: "https://image.tmdb.org/t/p/w342/ps2oKfhY6DL3alynlSqY97gHSsg.jpg",
        title: "Black Panther: Wakanda Forever",
        voteAverage: 0,
    },
    {
        genres: "Horror Mystery Thriller",
        resourceId: 760104,
        poster: "https://image.tmdb.org/t/p/w342/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
        title: "X",
        voteAverage: 6.8,
    },
    {
        genres: "Action Thriller",
        resourceId: 848123,
        poster: "https://image.tmdb.org/t/p/w342/ipn8khVVC4eToWiGf89WF9J5PJn.jpg",
        title: "Black Site",
        voteAverage: 7,
    },
    {
        genres: "Animation Adventure Action Fantasy",
        resourceId: 900667,
        poster: "https://image.tmdb.org/t/p/w342/m80kPdrmmtEh9wlLroCp0bwUGH0.jpg",
        title: "One Piece Film Red",
        voteAverage: 7.3,
    },
    {
        genres: "Drama Action",
        resourceId: 626872,
        poster: "https://image.tmdb.org/t/p/w342/h7kaQG5MbraSLibOuTpo0gtMxRz.jpg",
        title: "Emergency Declaration",
        voteAverage: 7.3,
    },
    {
        genres: "Animation Comedy Romance",
        resourceId: 820067,
        poster: "https://image.tmdb.org/t/p/w342/xTlAhTivEObHRFBKjAMVSyRQGv2.jpg",
        title: "The Quintessential Quintuplets Movie",
        voteAverage: 9.1,
    },
    {
        genres: "Comedy Romance",
        resourceId: 614939,
        poster: "https://image.tmdb.org/t/p/w342/4CArWLRroMPXwKJeO3HSYiyKyHD.jpg",
        title: "Bros",
        voteAverage: 7,
    },
    {
        genres: "Horror Thriller",
        resourceId: 676547,
        poster: "https://image.tmdb.org/t/p/w342/jXwYESgxqkXlYvoTyUTO2hqKK7T.jpg",
        title: "Prey for the Devil",
        voteAverage: 10,
    },
    {
        genres: "Drama Comedy",
        resourceId: 717151,
        poster: "https://image.tmdb.org/t/p/w342/6bcrhJQLoLNsYX4UGTOMQkCiACA.jpg",
        title: "The Phantom of the Open",
        voteAverage: 7,
    },
    {
        genres: "Comedy Drama",
        resourceId: 936074,
        poster: "https://image.tmdb.org/t/p/w342/14195Sv9rUHXJAuWbjFDtRQMUCf.jpg",
        title: "Tenor",
        voteAverage: 7.2,
    },
    {
        genres: "Comedy Family Music",
        resourceId: 830784,
        poster: "https://image.tmdb.org/t/p/w342/CpaU433AomkCvwAhR3KROUIFJO.jpg",
        title: "Lyle, Lyle, Crocodile",
        voteAverage: 6.2,
    },
    {
        genres: "Drama Thriller Action Adventure",
        resourceId: 698948,
        poster: "https://image.tmdb.org/t/p/w342/yi5KcJqFxy0D6yP8nCfcF8gJGg5.jpg",
        title: "Thirteen Lives",
        voteAverage: 8,
    },
    {
        genres: "Comedy Drama",
        resourceId: 754609,
        poster: "https://image.tmdb.org/t/p/w342/eUg0HDLhTEDcXGBU2iK6QRBILv4.jpg",
        title: "Mrs. Harris Goes to Paris",
        voteAverage: 7.5,
    },
    {
        genres: "Comedy Drama",
        resourceId: 757999,
        poster: "https://image.tmdb.org/t/p/w342/7BRRlZ5XWz9EC4pjPy66zKgQwCk.jpg",
        title: "Beautiful Minds",
        voteAverage: 7.6,
    },
    {
        genres: "Science Fiction Action Thriller",
        resourceId: 799379,
        poster: "https://image.tmdb.org/t/p/w342/h1pLOZATBr7oVDrwj3DfOjTOCGk.jpg",
        title: "Project Wolf Hunting",
        voteAverage: 6.7,
    },
    {
        genres: "Horror Comedy",
        resourceId: 800497,
        poster: "https://image.tmdb.org/t/p/w342/WoG2tvwanOMlU0qsbxpf9Qd3y.jpg",
        title: "Werewolves Within",
        voteAverage: 6.1,
    },
];
