export const movieList = [
    {
        id: 1,
        src: "/Dune.jpg",
        title: "Dune",
        imdb: "8.0",
        // likes: "88%",
        type: "action",
    },
    {
        id: 2,
        src: "/NoTimeToDie.jpg",
        title: "No Time To Die",
        imdb: "7.8",
        // likes: "80%",
        type: "Action/Thriller",
    },
    {
        id: 3,
        src: "Shangqi.jpg",
        title: "Shang-Chi and the Legend of the Ten Rings and what kind of ",
        imdb: "8.4",
        // likes: "70%",
        type: "action",
    },
    {
        id: 4,
        src: "/DontBreath2.jpg",
        title: "Dont Breath 2",
        imdb: "9.2",
        // likes: "90%",
        type: "action",
    },
    {
        id: 5,
        src: "/DontBreath2.jpg",
        title: "Dont Breath 2",
        imdb: "8.2",
        // likes: "90%",
        type: "action",
    },
    {
        id: 6,
        src: "/DontBreath2.jpg",
        title: "Dont Breath 2",
        imdb: "8.2",
        // likes: "90%",
        type: "action",
    },
    {
        id: 7,
        src: "/DontBreath2.jpg",
        title: "Dont Breath 2",
        imdb: "8.2",
        // likes: "90%",
        type: "action",
    },
];
